In [22]:
import datetime
import pandas
import requests

In [23]:
CLIENT_ID = "WnT3GXPouOHk3M7HfGx8-Q"
SECRET_KEY = "bNRMd0r9-WQSm6oKfYxeD7gvJvqyhw"
USERNAME = "panc86"
PASSWORD = "0412.Reddit"

In [24]:
auth = requests.auth.HTTPBasicAuth(CLIENT_ID, SECRET_KEY)
data = {"grant_type": "password", "username": USERNAME, "password": PASSWORD}
headers = {"User-Agent": "SMDRM/v0.1"}

In [25]:
# token id
response = requests.post("https://www.reddit.com/api/v1/access_token", auth=auth, data=data, headers=headers)
headers["Authorization"] = "bearer {access_token}".format(access_token=response.json()["access_token"])

In [26]:
# stream new feeds from subreddit
params = {"limit": 25}
response = requests.get("https://oauth.reddit.com/r/DisasterUpdate/new", headers=headers, params=params)
posts = (post["data"] for post in response.json()["data"]["children"])

In [27]:
df = pandas.DataFrame(dict(created_at=datetime.datetime.fromtimestamp(post["created_utc"]), id=post["name"], text=" ".join([post["title"], post["selftext"]])) for post in posts)
df

,created_at,id,text
0,2024-04-17 18:38:53,t3_1c6ek6r,Major floods due to heavy downpour in Al-Mukal...
1,2024-04-17 15:01:09,t3_1c698p3,Massive flooding due to extreme rains in Sharj...
2,2024-04-17 07:31:07,t3_1c61z7t,"April 15 or 16, 2024 - Ruang volcano in North ..."
3,2024-04-17 07:13:01,t3_1c61o2x,"Ruang volcano in North Sulawesi, IndonesiaðŸ‡®ðŸ‡© t..."
4,2024-04-17 04:49:03,t3_1c5z0gr,"April 17, 2024 - Samail, Oman - the flooding c..."
5,2024-04-17 04:26:06,t3_1c5yjpl,"April 16, Salem, Iowa, USA - Tornado!!! via X ..."
6,2024-04-17 03:36:05,t3_1c5xi6e,More video out of Dubai. Heavy flood at Sheikh...
7,2024-04-16 21:53:49,t3_1c5pkae,"Flash floods in Samail, Oman."
8,2024-04-16 20:06:08,t3_1c5mvz3,"April 16, 2024 - Dubai airport diverts arrival..."
9,2024-04-16 18:22:59,t3_1c5kao4,15/04/2024 - Tanzania - Torrential rain trigge...
10,2024-04-16 18:09:47,t3_1c5jz6k,Flooding at metro station due to extreme rains...
11,2024-04-16 13:33:40,t3_1c5dtgj,Major floods on the streets due to heavy rains...
12,2024-04-16 05:21:34,t3_1c560xu,"16 April 2024 - SundhnÃºkar, Iceland - Update! ..."
13,2024-04-16 03:21:10,t3_1c53kc3,"15/04/2024 - Manama, Bahrain - Heavy rains lea..."
14,2024-04-15 18:35:11,t3_1c4qp8a,"Kandahar, Afghanistan- April 14, 2024 - Floods..."
15,2024-04-15 17:37:29,t3_1c4p9wf,"14/04/2024 - Krakal, Indonesia - Floods overwh..."
16,2024-04-15 11:24:54,t3_1c4hw2w,"Floods due to extreme rains in Quriyat, Oman ðŸ‡´..."
17,2024-04-15 11:19:01,t3_1c4hswy,Heavy floods due to torrential rainfall in Mar...
18,2024-04-14 20:54:30,t3_1c410s9,Forest fire out of control in TÃ rbena of Alica...
19,2024-04-14 17:13:09,t3_1c3vu9u,Major floods due to extreme rains in Al Mudhai...
20,2024-04-14 07:36:59,t3_1c3m2k5,"14/04/2024 - Ibri, Oman - Massive flooding due..."
21,2024-04-14 07:25:46,t3_1c3lw7y,"April 13, 2024 - Ebeko, Paramushir Island, Rus..."
22,2024-04-14 07:23:18,t3_1c3luro,"13/04/2024 - Villarrica, AraucanÃ­a, Chile - Li..."
23,2024-04-14 00:11:12,t3_1c3dnam,"April 13, 2024 A hailstorm and heavy rain caus..."
24,2024-04-14 00:09:15,t3_1c3dlpr,"14 April 2024 - Lewotolok, Lembata Island, Ind..."

In [28]:
# search feeds
response = requests.get("https://oauth.reddit.com/search.json?", headers=headers, params={"q": "dubai flood", "limit": 100, "after": 1711922400})

In [29]:
response.url

'https://oauth.reddit.com/search.json?q=dubai+flood&limit=100&after=1711922400'

In [30]:
posts = (post["data"] for post in response.json()["data"]["children"])
df = pandas.DataFrame(dict(created_at=datetime.datetime.fromtimestamp(post["created_utc"]), id=post["name"], text=" ".join([post["title"], post["selftext"]])) for post in posts)
df.sort_values("created_at")

,created_at,id,text
4,2020-01-13 01:34:34,t3_enwbsd,Flash flood in Dubai desert captured on a drone!
81,2020-01-13 01:37:46,t3_enwd8o,Flash flood in Dubai desert captured on a drone!
21,2022-02-23 17:46:49,t3_szlwke,"Calling Dubai's Infamous ""Massage"" Cards... Wh..."
9,2022-07-29 01:30:43,t3_waot7e,Floods in Dubai
1,2022-07-29 11:18:08,t3_wb02fm,This flood in Dubai
...,...,...,...
88,2024-04-17 17:54:16,t3_1c6des1,Amazing - See how flood waters entering Dubai ...
27,2024-04-17 17:55:24,t3_1c6dfs9,TOWIE people stranded after Dubai floods ! I a...
40,2024-04-17 18:01:04,t3_1c6dl2u,Dubai flooding in pictures: City reeling after...
91,2024-04-17 18:45:33,t3_1c6epyi,[ME] - In pictures: Unprecedented storm floods...
95,2024-04-17 19:00:42,t3_1c6f3dn,[World] - Airport runway submerged in Dubai fl...

In [20]:
import praw
from pmaw import PushshiftAPI

reddit = praw.Reddit(
 client_id=CLIENT_ID,
 client_secret=SECRET_KEY,
 user_agent=f'python: PMAW request enrichment (by u/panc86)'
)

api = PushshiftAPI(praw=reddit)
#data = api.search_submissions(q="quantum", subreddit="science")#, limit=100), since=1711922400)
data = api.search_comments(q="quantum", subreddit="science")
list(data)

Not all PushShift shards are active. Query results may be incomplete.

[]